main: x.KenKOfficial.AntyBot.Basic.Main
version: 1.0-Beta
name: xKenAntyBot
author: xKenKOfficial
description: Plugin Autorstwa KenKOfficial
website: https://discord.gg/2HDuZrEFTg

commands:
  blacklist:
  unblacklist: